name: CI

on:
  push:

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1

    - uses: actions/setup-go@v5
      with:
        go-version: '>=1.23'

    - name: Test
      run: |
        go test -covermode=count -coverprofile=coverage.out -v ./...


    - name: gosec
      run: |
        go install github.com/securego/gosec/v2/cmd/gosec@latest
        gosec ./...

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.1

    - name: Archive stuff
      uses: actions/upload-artifact@v4.0.0
      with:
        name: build-artefacts
        path: |
          coverage.out
